import Button from '@/components/Button'
import Form from '@/components/Form'
import Input from '@/components/Input'
import Label from '@/components/Label'
import Option from '@/components/Option'
import Radio from '@/components/Radio'
import Select from '@/components/Select'
import TextArea from '@/components/TextArea'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Form>
        <Label htmlFor="name">Nome</Label>
        <Input />
        <Label htmlFor="email">Email</Label>
        <Input />
        <Label htmlFor="password">Sexo</Label>
        <Radio name="sexo" /><p>Masculino</p>
        <Radio name="sexo" /><p>Feminino</p>
        <Label htmlFor="curso">Curso</Label>
        <Select>
          <Option value="1">Html e Css</Option>
          <Option value="2">Javascript</Option>
          <Option value="3">React</Option>
        </Select>
        <Label htmlFor="atendimento">Descreva o Atendimento especial:</Label>
        <TextArea>

        </TextArea>
        <Button>Realizar Inscrição</Button>
      </Form>

    </>
  )
}
